spring:
  application:
    name: spring-security-test

  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: welcome123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#debug: true

server:
  port: 1000


